export const RoomActionType = {
  GET_LIST_ROOM: 'GET_LIST_ROOM',
  CHANGE_ACTIVE_ROOM: 'CHANGE_ACTIVE_ROOM',
  CHANGE_TOP_ROOM: 'CHANGE_TOP_ROOM',
  SET_MESSAGE: 'SET_MESSAGE',
  MOVE_TOP_ROOM: 'MOVE_TOP_ROOM',
  UPDATE_TYPING_ACTIVE_ROOM: 'UPDATE_TYPING_ACTIVE_ROOM',
  UPDATE_STATUS_USER: 'UPDATE_STATUS_USER',
  UPDATE_READ_MESSAGE: 'UPDATE_READ_MESSAGE',
};
